[build]
  command = "npm run build"
  publish = "dist/assignment"

# Optional: set Node version for Netlify build
[build.environment]
  NODE_VERSION = "22"

# redirect rules (alternative to src/_redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
